import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const categories = [
    { name: 'Medical', slug: 'medical', description: 'Diet plans for medical conditions', icon: '🏥', color: '#4CAF50' },
    { name: 'Fitness', slug: 'fitness', description: 'Nutrition for workout performance', icon: '💪', color: '#2196F3' },
    { name: 'Skin & Looks', slug: 'skin-looks', description: 'Beauty-focused diets', icon: '✨', color: '#E91E63' },
    { name: 'Athletic', slug: 'athletic', description: 'High-performance nutrition', icon: '🏃', color: '#FF9800' },
];

const dietPlans = [
    // ==================== MEDICAL - VEGETARIAN (5) ====================
    { categorySlug: 'medical', dietType: 'vegetarian', title: 'Type 2 Diabetes Control', description: 'Manage blood sugar with low GI foods', duration: 'Ongoing', difficulty: 'Intermediate', calories: 1800, protein: 80, carbs: 180, fats: 70, benefits: ['Sugar control', 'Weight loss'], restrictions: ['No refined sugar'], meals: [{ time: 'Breakfast', items: ['Steel cut oats', 'Almonds'], calories: 400 }] },
    { categorySlug: 'medical', dietType: 'vegetarian', title: 'DASH Hypertension Plan', description: 'Lower blood pressure naturally', duration: '30 days', difficulty: 'Beginner', calories: 1900, protein: 85, carbs: 240, fats: 60, benefits: ['Lower BP', 'Heart health'], restrictions: ['Low sodium'], meals: [{ time: 'Breakfast', items: ['Whole grain cereal', 'Banana'], calories: 350 }] },
    { categorySlug: 'medical', dietType: 'vegetarian', title: 'Kidney-Friendly Diet', description: 'Balanced for kidney health', duration: 'Ongoing', difficulty: 'Advanced', calories: 1700, protein: 50, carbs: 220, fats: 65, benefits: ['Kidney protection'], restrictions: ['Low protein', 'Low potassium'], meals: [{ time: 'Dinner', items: ['White rice', 'Steamed cabbage'], calories: 450 }] },
    { categorySlug: 'medical', dietType: 'vegetarian', title: 'GERD Relief Diet', description: 'Soothe acid reflux', duration: '21 days', difficulty: 'Easy', calories: 1800, protein: 75, carbs: 230, fats: 60, benefits: ['Reduced reflux', 'Better sleep'], restrictions: ['No spicy', 'No citrus'], meals: [{ time: 'Dinner', items: ['Mashed potato', 'Green beans'], calories: 500 }] },
    { categorySlug: 'medical', dietType: 'vegetarian', title: 'IBS Gentle Diet', description: 'Low FODMAP for digestive comfort', duration: '28 days', difficulty: 'Advanced', calories: 1700, protein: 75, carbs: 200, fats: 60, benefits: ['Less bloating', 'Regular digestion'], restrictions: ['Low FODMAP'], meals: [{ time: 'Lunch', items: ['Rice noodles', 'Carrots'], calories: 500 }] },
    // ==================== MEDICAL - VEGAN (5) ====================
    { categorySlug: 'medical', dietType: 'vegan', title: 'Cholesterol Lowering', description: 'Plant sterols to reduce LDL', duration: '90 days', difficulty: 'Intermediate', calories: 1800, protein: 70, carbs: 250, fats: 50, benefits: ['Lower LDL', 'Heart health'], restrictions: ['No saturated fat'], meals: [{ time: 'Breakfast', items: ['Oatmeal with flax', 'Almonds'], calories: 400 }] },
    { categorySlug: 'medical', dietType: 'vegan', title: 'Liver Detox Protocol', description: 'Cleansing whole foods', duration: '14 days', difficulty: 'Easy', calories: 1600, protein: 60, carbs: 220, fats: 45, benefits: ['Liver support', 'Energy'], restrictions: ['No alcohol'], meals: [{ time: 'Breakfast', items: ['Lemon water', 'Green smoothie'], calories: 300 }] },
    { categorySlug: 'medical', dietType: 'vegan', title: 'Anti-Cancer Nutrition', description: 'Antioxidant-rich plant foods', duration: '60 days', difficulty: 'Intermediate', calories: 1750, protein: 65, carbs: 240, fats: 50, benefits: ['Cell protection', 'Immunity'], restrictions: ['No processed foods'], meals: [{ time: 'Lunch', items: ['Broccoli', 'Turmeric rice', 'Berries'], calories: 550 }] },
    { categorySlug: 'medical', dietType: 'vegan', title: 'Migraine Prevention', description: 'Avoid trigger foods naturally', duration: '30 days', difficulty: 'Intermediate', calories: 1800, protein: 70, carbs: 230, fats: 55, benefits: ['Fewer headaches', 'Stable energy'], restrictions: ['No tyramine foods', 'No MSG'], meals: [{ time: 'Dinner', items: ['Quinoa bowl', 'Vegetables'], calories: 500 }] },
    { categorySlug: 'medical', dietType: 'vegan', title: 'Bone Health Builder', description: 'Calcium-rich plant sources', duration: '90 days', difficulty: 'Easy', calories: 1850, protein: 75, carbs: 250, fats: 55, benefits: ['Strong bones', 'Calcium absorption'], restrictions: ['High calcium foods'], meals: [{ time: 'Lunch', items: ['Fortified tofu', 'Kale', 'Sesame seeds'], calories: 550 }] },
    // ==================== MEDICAL - NON-VEG (5) ====================
    { categorySlug: 'medical', dietType: 'non-vegetarian', title: 'Heart Healthy Mediterranean', description: 'Olive oil and fish for heart', duration: 'Ongoing', difficulty: 'Easy', calories: 2000, protein: 90, carbs: 250, fats: 70, benefits: ['Heart health', 'Longevity'], restrictions: ['Low red meat'], meals: [{ time: 'Lunch', items: ['Grilled salmon', 'Greek salad'], calories: 650 }] },
    { categorySlug: 'medical', dietType: 'non-vegetarian', title: 'Anti-Inflammatory Protocol', description: 'Omega-3 rich for inflammation', duration: '60 days', difficulty: 'Intermediate', calories: 1850, protein: 95, carbs: 200, fats: 75, benefits: ['Reduced pain', 'Joint health'], restrictions: ['No processed foods'], meals: [{ time: 'Lunch', items: ['Wild salmon', 'Turmeric rice'], calories: 600 }] },
    { categorySlug: 'medical', dietType: 'non-vegetarian', title: 'Thyroid Support Plan', description: 'Iodine and selenium rich', duration: '45 days', difficulty: 'Intermediate', calories: 1900, protein: 90, carbs: 210, fats: 70, benefits: ['Hormone balance', 'Energy'], restrictions: ['Limit goitrogens'], meals: [{ time: 'Lunch', items: ['Seaweed salad', 'Grilled fish'], calories: 550 }] },
    { categorySlug: 'medical', dietType: 'non-vegetarian', title: 'Post-Surgery Recovery', description: 'High protein for healing', duration: '30 days', difficulty: 'Beginner', calories: 2100, protein: 120, carbs: 220, fats: 70, benefits: ['Faster healing', 'Tissue repair'], restrictions: ['High protein'], meals: [{ time: 'Dinner', items: ['Chicken breast', 'Mashed potato', 'Vegetables'], calories: 700 }] },
    { categorySlug: 'medical', dietType: 'non-vegetarian', title: 'Anemia Fighter', description: 'Iron-rich diet for blood health', duration: '60 days', difficulty: 'Easy', calories: 1900, protein: 95, carbs: 220, fats: 60, benefits: ['Higher iron', 'Energy'], restrictions: ['High iron foods'], meals: [{ time: 'Lunch', items: ['Beef liver', 'Spinach', 'Vitamin C fruit'], calories: 600 }] },

    // ==================== FITNESS - VEGETARIAN (5) ====================
    { categorySlug: 'fitness', dietType: 'vegetarian', title: 'Vegetarian Strength Gains', description: 'Dairy and plant proteins for muscle', duration: '8 weeks', difficulty: 'Intermediate', calories: 2300, protein: 160, carbs: 280, fats: 70, benefits: ['Muscle growth', 'Ethical gains'], restrictions: ['Vegetarian'], meals: [{ time: 'Lunch', items: ['Paneer curry', 'Quinoa'], calories: 700 }] },
    { categorySlug: 'fitness', dietType: 'vegetarian', title: 'High Protein Vegetarian', description: 'Maximize protein without meat', duration: '8 weeks', difficulty: 'Intermediate', calories: 2200, protein: 150, carbs: 250, fats: 65, benefits: ['Muscle support', 'Recovery'], restrictions: ['High protein'], meals: [{ time: 'Lunch', items: ['Greek yogurt', 'Nuts', 'Cottage cheese'], calories: 600 }] },
    { categorySlug: 'fitness', dietType: 'vegetarian', title: 'Egg-Based Muscle Plan', description: 'Eggs as primary protein source', duration: '6 weeks', difficulty: 'Beginner', calories: 2400, protein: 170, carbs: 260, fats: 80, benefits: ['Complete protein', 'Budget friendly'], restrictions: ['Eggs daily'], meals: [{ time: 'Breakfast', items: ['6 eggs', 'Toast', 'Avocado'], calories: 650 }] },
    { categorySlug: 'fitness', dietType: 'vegetarian', title: 'Lacto-Ovo Bulk', description: 'Dairy and eggs for clean bulk', duration: '12 weeks', difficulty: 'Intermediate', calories: 2600, protein: 160, carbs: 320, fats: 80, benefits: ['Clean gains', 'Strength'], restrictions: ['High dairy'], meals: [{ time: 'Post-workout', items: ['Whey shake', 'Banana', 'Oats'], calories: 500 }] },
    { categorySlug: 'fitness', dietType: 'vegetarian', title: 'Yoga Fitness Fusion', description: 'Light meals for active yoga practice', duration: '8 weeks', difficulty: 'Easy', calories: 1900, protein: 90, carbs: 260, fats: 55, benefits: ['Flexibility', 'Lean body'], restrictions: ['Light meals'], meals: [{ time: 'Lunch', items: ['Lentil soup', 'Brown rice', 'Vegetables'], calories: 500 }] },
    // ==================== FITNESS - VEGAN (5) ====================
    { categorySlug: 'fitness', dietType: 'vegan', title: 'Vegan Powerlifting', description: 'High-calorie plant-based for lifting', duration: '10 weeks', difficulty: 'Advanced', calories: 2800, protein: 150, carbs: 350, fats: 90, benefits: ['Strength', 'Recovery'], restrictions: ['Vegan'], meals: [{ time: 'Dinner', items: ['Seitan stir-fry', 'Brown rice'], calories: 800 }] },
    { categorySlug: 'fitness', dietType: 'vegan', title: 'Vegan Muscle Builder', description: 'Complete plant proteins for growth', duration: '12 weeks', difficulty: 'Advanced', calories: 2600, protein: 160, carbs: 300, fats: 85, benefits: ['Muscle growth', 'Ethical'], restrictions: ['Vegan'], meals: [{ time: 'Lunch', items: ['Tempeh', 'Quinoa', 'Black beans'], calories: 700 }] },
    { categorySlug: 'fitness', dietType: 'vegan', title: 'Plant-Based Shred', description: 'Cutting while staying vegan', duration: '8 weeks', difficulty: 'Advanced', calories: 1800, protein: 130, carbs: 180, fats: 60, benefits: ['Fat loss', 'Muscle retention'], restrictions: ['Vegan', 'Deficit'], meals: [{ time: 'Dinner', items: ['Tofu', 'Vegetables', 'Quinoa'], calories: 500 }] },
    { categorySlug: 'fitness', dietType: 'vegan', title: 'Soy-Free Vegan Muscle', description: 'Build muscle without soy products', duration: '10 weeks', difficulty: 'Advanced', calories: 2500, protein: 140, carbs: 300, fats: 80, benefits: ['Muscle growth', 'Soy-free'], restrictions: ['No soy'], meals: [{ time: 'Lunch', items: ['Lentils', 'Hemp seeds', 'Pea protein'], calories: 650 }] },
    { categorySlug: 'fitness', dietType: 'vegan', title: 'Vegan HIIT Fuel', description: 'High energy for interval training', duration: '6 weeks', difficulty: 'Intermediate', calories: 2200, protein: 110, carbs: 300, fats: 65, benefits: ['Energy', 'Recovery'], restrictions: ['Vegan'], meals: [{ time: 'Pre-workout', items: ['Banana', 'Oats', 'Almond butter'], calories: 400 }] },
    // ==================== FITNESS - NON-VEG (5) ====================
    { categorySlug: 'fitness', dietType: 'non-vegetarian', title: 'Lean Muscle Builder', description: 'Classic high-protein bodybuilding', duration: '12 weeks', difficulty: 'Intermediate', calories: 2500, protein: 200, carbs: 250, fats: 70, benefits: ['Muscle hypertrophy', 'Strength'], restrictions: ['Track macros'], meals: [{ time: 'Lunch', items: ['Grilled chicken', 'Rice', 'Broccoli'], calories: 700 }] },
    { categorySlug: 'fitness', dietType: 'non-vegetarian', title: 'Shredding Cut Phase', description: 'Deficit with high protein', duration: '8 weeks', difficulty: 'Advanced', calories: 1800, protein: 180, carbs: 150, fats: 50, benefits: ['Fat loss', 'Definition'], restrictions: ['Calorie deficit'], meals: [{ time: 'Dinner', items: ['Fish', 'Vegetables', 'Small rice'], calories: 450 }] },
    { categorySlug: 'fitness', dietType: 'non-vegetarian', title: 'Keto Shred', description: 'Ultra-low carb for rapid fat loss', duration: '6 weeks', difficulty: 'Advanced', calories: 1900, protein: 140, carbs: 30, fats: 140, benefits: ['Rapid fat loss', 'Mental clarity'], restrictions: ['Under 50g carbs'], meals: [{ time: 'Dinner', items: ['Steak', 'Avocado', 'Spinach'], calories: 700 }] },
    { categorySlug: 'fitness', dietType: 'non-vegetarian', title: 'Lean Bulk Protocol', description: 'Slow surplus for clean gains', duration: '16 weeks', difficulty: 'Intermediate', calories: 2700, protein: 180, carbs: 320, fats: 80, benefits: ['Muscle gain', 'Minimal fat'], restrictions: ['Clean foods'], meals: [{ time: 'Post-workout', items: ['Whey', 'Chicken', 'Rice'], calories: 600 }] },
    { categorySlug: 'fitness', dietType: 'non-vegetarian', title: 'CrossFit Performance', description: 'Zone diet for functional fitness', duration: '12 weeks', difficulty: 'Advanced', calories: 2400, protein: 170, carbs: 240, fats: 80, benefits: ['Performance', 'Endurance'], restrictions: ['Zone blocks'], meals: [{ time: 'Pre-workout', items: ['Chicken', 'Sweet potato', 'Veggies'], calories: 500 }] },

    // ==================== SKIN & LOOKS - VEGETARIAN (5) ====================
    { categorySlug: 'skin-looks', dietType: 'vegetarian', title: 'Glowing Skin Detox', description: 'Antioxidant-rich for radiance', duration: '21 days', difficulty: 'Beginner', calories: 1600, protein: 60, carbs: 200, fats: 50, benefits: ['Luminous skin', 'Reduced inflammation'], restrictions: ['No meat'], meals: [{ time: 'Breakfast', items: ['Papaya bowl', 'Green tea'], calories: 300 }] },
    { categorySlug: 'skin-looks', dietType: 'vegetarian', title: 'Acne Fighting Protocol', description: 'Low glycemic to reduce breakouts', duration: '28 days', difficulty: 'Intermediate', calories: 1700, protein: 80, carbs: 180, fats: 60, benefits: ['Clearer skin', 'Hormonal balance'], restrictions: ['No dairy', 'Low sugar'], meals: [{ time: 'Lunch', items: ['Leafy greens', 'Avocado', 'Eggs'], calories: 550 }] },
    { categorySlug: 'skin-looks', dietType: 'vegetarian', title: 'Vitamin C Boost', description: 'Citrus for collagen synthesis', duration: '21 days', difficulty: 'Easy', calories: 1650, protein: 65, carbs: 220, fats: 50, benefits: ['Brighter skin', 'Even tone'], restrictions: ['High vitamin C'], meals: [{ time: 'Breakfast', items: ['Orange juice', 'Kiwi', 'Berries'], calories: 350 }] },
    { categorySlug: 'skin-looks', dietType: 'vegetarian', title: 'Sugar-Free Glow', description: 'Eliminate sugar for youthful skin', duration: '30 days', difficulty: 'Advanced', calories: 1700, protein: 85, carbs: 150, fats: 70, benefits: ['Less glycation', 'Clearer skin'], restrictions: ['Zero added sugar'], meals: [{ time: 'Lunch', items: ['Grilled vegetables', 'Quinoa'], calories: 500 }] },
    { categorySlug: 'skin-looks', dietType: 'vegetarian', title: 'Probiotic Skin Health', description: 'Gut-skin axis for clear complexion', duration: '30 days', difficulty: 'Easy', calories: 1750, protein: 70, carbs: 210, fats: 55, benefits: ['Clear skin', 'Gut health'], restrictions: ['Fermented foods daily'], meals: [{ time: 'Breakfast', items: ['Greek yogurt', 'Kefir', 'Sauerkraut'], calories: 400 }] },
    // ==================== SKIN & LOOKS - VEGAN (5) ====================
    { categorySlug: 'skin-looks', dietType: 'vegan', title: 'Plant-Based Radiance', description: '100% plant-based for skin clarity', duration: '14 days', difficulty: 'Beginner', calories: 1500, protein: 50, carbs: 220, fats: 40, benefits: ['Clear complexion', 'Detox'], restrictions: ['Vegan'], meals: [{ time: 'Breakfast', items: ['Green smoothie', 'Chia pudding'], calories: 350 }] },
    { categorySlug: 'skin-looks', dietType: 'vegan', title: 'Hydration Glow Plan', description: 'Water-rich foods for plump skin', duration: '14 days', difficulty: 'Beginner', calories: 1500, protein: 55, carbs: 210, fats: 40, benefits: ['Hydrated skin', 'Elasticity'], restrictions: ['High water content'], meals: [{ time: 'Snack', items: ['Watermelon', 'Cucumber'], calories: 150 }] },
    { categorySlug: 'skin-looks', dietType: 'vegan', title: 'Vegan Anti-Aging', description: 'Plant antioxidants for youth', duration: '60 days', difficulty: 'Intermediate', calories: 1700, protein: 60, carbs: 230, fats: 55, benefits: ['Reduced wrinkles', 'Vitality'], restrictions: ['Vegan'], meals: [{ time: 'Lunch', items: ['Kale salad', 'Berries', 'Nuts'], calories: 500 }] },
    { categorySlug: 'skin-looks', dietType: 'vegan', title: 'Green Beauty Diet', description: 'Chlorophyll-rich for detox glow', duration: '21 days', difficulty: 'Easy', calories: 1550, protein: 55, carbs: 200, fats: 50, benefits: ['Detox', 'Glow'], restrictions: ['High greens'], meals: [{ time: 'Lunch', items: ['Spinach', 'Chlorella', 'Green juice'], calories: 400 }] },
    { categorySlug: 'skin-looks', dietType: 'vegan', title: 'Alkaline Beauty', description: 'pH balanced eating for skin', duration: '28 days', difficulty: 'Intermediate', calories: 1600, protein: 55, carbs: 220, fats: 45, benefits: ['Balanced pH', 'Clear skin'], restrictions: ['Alkaline foods'], meals: [{ time: 'Dinner', items: ['Avocado', 'Leafy greens', 'Almonds'], calories: 450 }] },
    // ==================== SKIN & LOOKS - NON-VEG (5) ====================
    { categorySlug: 'skin-looks', dietType: 'non-vegetarian', title: 'Collagen Booster', description: 'Bone broth and fish for firm skin', duration: '30 days', difficulty: 'Intermediate', calories: 1800, protein: 100, carbs: 150, fats: 70, benefits: ['Firm skin', 'Joint health'], restrictions: ['Collagen sources'], meals: [{ time: 'Breakfast', items: ['Bone broth', 'Eggs', 'Avocado'], calories: 450 }] },
    { categorySlug: 'skin-looks', dietType: 'non-vegetarian', title: 'Anti-Aging Nutrition', description: 'Nutrient-dense for youthful looks', duration: '90 days', difficulty: 'Intermediate', calories: 1850, protein: 80, carbs: 200, fats: 65, benefits: ['Reduced wrinkles', 'Elasticity'], restrictions: ['No processed foods'], meals: [{ time: 'Lunch', items: ['Salmon', 'Sweet potato', 'Greens'], calories: 650 }] },
    { categorySlug: 'skin-looks', dietType: 'non-vegetarian', title: 'Hair Growth Formula', description: 'Biotin and protein for hair', duration: '60 days', difficulty: 'Easy', calories: 1800, protein: 90, carbs: 200, fats: 60, benefits: ['Hair growth', 'Stronger nails'], restrictions: ['High biotin'], meals: [{ time: 'Lunch', items: ['Eggs', 'Salmon', 'Spinach'], calories: 600 }] },
    { categorySlug: 'skin-looks', dietType: 'non-vegetarian', title: 'Omega-3 Skin Repair', description: 'Fatty fish for skin barrier', duration: '30 days', difficulty: 'Intermediate', calories: 1900, protein: 95, carbs: 180, fats: 80, benefits: ['Skin repair', 'Less dryness'], restrictions: ['High omega-3'], meals: [{ time: 'Dinner', items: ['Mackerel', 'Flax seeds', 'Avocado'], calories: 650 }] },
    { categorySlug: 'skin-looks', dietType: 'non-vegetarian', title: 'Zinc Clear Skin', description: 'Zinc-rich foods for acne control', duration: '30 days', difficulty: 'Easy', calories: 1800, protein: 95, carbs: 190, fats: 65, benefits: ['Acne control', 'Healing'], restrictions: ['High zinc foods'], meals: [{ time: 'Dinner', items: ['Oysters', 'Beef', 'Pumpkin seeds'], calories: 600 }] },

    // ==================== ATHLETIC - VEGETARIAN (5) ====================
    { categorySlug: 'athletic', dietType: 'vegetarian', title: 'Rock Climber Strength', description: 'Lean protein for grip and endurance', duration: '10 weeks', difficulty: 'Intermediate', calories: 2200, protein: 140, carbs: 250, fats: 65, benefits: ['Grip strength', 'Lean body'], restrictions: ['Lean mass focus'], meals: [{ time: 'Lunch', items: ['Greek yogurt', 'Nuts', 'Protein bar'], calories: 550 }] },
    { categorySlug: 'athletic', dietType: 'vegetarian', title: 'Swimmer Vegetarian', description: 'Balanced nutrition for pool athletes', duration: '12 weeks', difficulty: 'Intermediate', calories: 2500, protein: 130, carbs: 320, fats: 70, benefits: ['Energy', 'Recovery'], restrictions: ['Pre-pool timing'], meals: [{ time: 'Pre-pool', items: ['Pasta', 'Vegetables', 'Eggs'], calories: 650 }] },
    { categorySlug: 'athletic', dietType: 'vegetarian', title: 'Tennis Energy Plan', description: 'Quick energy for court sports', duration: '8 weeks', difficulty: 'Easy', calories: 2300, protein: 110, carbs: 300, fats: 70, benefits: ['Agility', 'Stamina'], restrictions: ['Quick energy foods'], meals: [{ time: 'Match day', items: ['Banana', 'Energy bar', 'Electrolytes'], calories: 400 }] },
    { categorySlug: 'athletic', dietType: 'vegetarian', title: 'Cyclist Vegetarian', description: 'Carb cycling for road cyclists', duration: '10 weeks', difficulty: 'Advanced', calories: 2700, protein: 120, carbs: 380, fats: 70, benefits: ['Endurance', 'Performance'], restrictions: ['Carb timing'], meals: [{ time: 'Pre-ride', items: ['Oatmeal', 'Banana', 'Honey'], calories: 600 }] },
    { categorySlug: 'athletic', dietType: 'vegetarian', title: 'Soccer Performance', description: 'High energy for field sports', duration: '12 weeks', difficulty: 'Intermediate', calories: 2400, protein: 120, carbs: 310, fats: 70, benefits: ['Stamina', 'Speed'], restrictions: ['Balanced macros'], meals: [{ time: 'Pre-game', items: ['Pasta', 'Cheese', 'Vegetables'], calories: 650 }] },
    // ==================== ATHLETIC - VEGAN (5) ====================
    { categorySlug: 'athletic', dietType: 'vegan', title: 'Sprinter Explosive Power', description: 'Plant-based for short-burst sports', duration: '8 weeks', difficulty: 'Advanced', calories: 2600, protein: 140, carbs: 300, fats: 80, benefits: ['Explosive energy', 'Lean physique'], restrictions: ['Vegan'], meals: [{ time: 'Lunch', items: ['Tempeh tacos', 'Guacamole'], calories: 750 }] },
    { categorySlug: 'athletic', dietType: 'vegan', title: 'Yoga & Flexibility Diet', description: 'Light plant-based for yogis', duration: '8 weeks', difficulty: 'Easy', calories: 1800, protein: 70, carbs: 250, fats: 55, benefits: ['Flexibility', 'Mindfulness'], restrictions: ['Vegan'], meals: [{ time: 'Breakfast', items: ['Fruit bowl', 'Nuts', 'Green tea'], calories: 350 }] },
    { categorySlug: 'athletic', dietType: 'vegan', title: 'Vegan Marathon Fuel', description: 'High-carb plant-based for runners', duration: '16 weeks', difficulty: 'Advanced', calories: 2900, protein: 110, carbs: 420, fats: 70, benefits: ['Endurance', 'Recovery'], restrictions: ['Vegan'], meals: [{ time: 'Pre-run', items: ['Oatmeal', 'Dates', 'Almond butter'], calories: 700 }] },
    { categorySlug: 'athletic', dietType: 'vegan', title: 'Triathlete Plant Fuel', description: 'Multi-sport vegan nutrition', duration: '20 weeks', difficulty: 'Advanced', calories: 3200, protein: 130, carbs: 450, fats: 85, benefits: ['Multi-sport endurance', 'Adaptation'], restrictions: ['Vegan'], meals: [{ time: 'During training', items: ['Energy gels', 'Dates', 'Electrolytes'], calories: 400 }] },
    { categorySlug: 'athletic', dietType: 'vegan', title: 'Hiking Endurance', description: 'Trail-ready plant nutrition', duration: '8 weeks', difficulty: 'Intermediate', calories: 2400, protein: 100, carbs: 320, fats: 75, benefits: ['Sustained energy', 'Light pack'], restrictions: ['Vegan', 'Portable foods'], meals: [{ time: 'Trail snack', items: ['Trail mix', 'Dried fruit', 'Energy bar'], calories: 400 }] },
    // ==================== ATHLETIC - NON-VEG (5) ====================
    { categorySlug: 'athletic', dietType: 'non-vegetarian', title: 'Marathon Runner Fuel', description: 'High-carb for endurance athletes', duration: '16 weeks', difficulty: 'Advanced', calories: 3000, protein: 120, carbs: 450, fats: 60, benefits: ['Endurance', 'Glycogen storage'], restrictions: ['Timing centered'], meals: [{ time: 'Breakfast', items: ['Oatmeal', 'Eggs', 'Banana'], calories: 700 }] },
    { categorySlug: 'athletic', dietType: 'non-vegetarian', title: 'MMA Fighter Prep', description: 'Balanced macros with weight control', duration: '8 weeks', difficulty: 'Advanced', calories: 2400, protein: 180, carbs: 250, fats: 70, benefits: ['Strength', 'Weight control'], restrictions: ['Weight class management'], meals: [{ time: 'Lunch', items: ['Lean beef', 'Rice', 'Vegetables'], calories: 650 }] },
    { categorySlug: 'athletic', dietType: 'non-vegetarian', title: 'Basketball Performance', description: 'High energy for court athletes', duration: '12 weeks', difficulty: 'Intermediate', calories: 2700, protein: 150, carbs: 350, fats: 70, benefits: ['Agility', 'Jump power'], restrictions: ['Hydration focus'], meals: [{ time: 'Pre-game', items: ['Chicken sandwich', 'Fruit'], calories: 600 }] },
    { categorySlug: 'athletic', dietType: 'non-vegetarian', title: 'Triathlete Fuel System', description: 'Multi-sport nutrition', duration: '20 weeks', difficulty: 'Advanced', calories: 3500, protein: 150, carbs: 500, fats: 90, benefits: ['Multi-sport endurance', 'Adaptation'], restrictions: ['Periodized nutrition'], meals: [{ time: 'During', items: ['Energy bars', 'Gels', 'Electrolytes'], calories: 400 }] },
    { categorySlug: 'athletic', dietType: 'non-vegetarian', title: 'Team Sport Recovery', description: 'Post-game recovery nutrition', duration: 'Ongoing', difficulty: 'Beginner', calories: 2500, protein: 130, carbs: 320, fats: 70, benefits: ['Fast recovery', 'Muscle repair'], restrictions: ['Post-game timing'], meals: [{ time: 'Post-game', items: ['Chocolate milk', 'Turkey sandwich'], calories: 600 }] },
];

async function main() {
    console.log('🌱 Starting database seed...');
    await prisma.chatMessage.deleteMany();
    await prisma.chatHistory.deleteMany();
    await prisma.userPlan.deleteMany();
    await prisma.dietPlan.deleteMany();
    await prisma.category.deleteMany();
    await prisma.user.deleteMany(); // Clear users ensuring we don't have duplicates for the default email

    console.log('👤 Creating default user...');
    const defaultUser = await prisma.user.create({
        data: {
            email: 'guest@dietai.com',
            password: 'guest_password_mode', // In secure app, this would be hashed
            name: 'Guest User',
            image: 'https://api.iconify.design/mdi:account-circle.svg?color=%23000000',
        }
    });
    console.log(`   ✓ User created: ${defaultUser.email} (${defaultUser.id})`);

    console.log('✨ Creating categories...');
    const cats: any = {};
    for (const c of categories) { cats[c.slug] = await prisma.category.create({ data: c }); console.log(`   ✓ ${c.name}`); }

    console.log('📋 Creating 60 diet plans (5 per diet type × 4 categories)...');
    for (const p of dietPlans) {
        await prisma.dietPlan.create({ data: { title: p.title, description: p.description, duration: p.duration, difficulty: p.difficulty, calories: p.calories, protein: p.protein, carbs: p.carbs, fats: p.fats, benefits: p.benefits, restrictions: p.restrictions, meals: p.meals, categoryId: cats[p.categorySlug].id, dietType: p.dietType } });
        console.log(`   ✓ ${p.title} (${p.dietType})`);
    }
    console.log('✅ Database seeded with 60 diet plans!');
}

main().catch(e => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
